server:
  port: 80
spring:
  application:
    name: cloud-providerconsul-order
  cloud:
    consul:
      host: 192.168.182.130
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register-health-check: false