server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/buludiudiu/springcloud-config.git
          search-paths:
            - springcloud-config
          #username: buludiudiu
          #password: guan0808+
      label: master
  rabbitmq:
    host: 192.168.182.130
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka


management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'