server:
  port: 8401
spring:
  application:
    name: cloudclibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.182.144:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.182.144:8848
            dataId: cloudclibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'
